---
title: "test"
author: "Catherine Rohner"
date: "2024-03-22"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(AnnotationHub)
  library(ensembldb)
  library(GenomicRanges)
  library(epiwraps)
  library(rtracklayer)
  library(ggplot2)
})
```


```{r}
H3K27me3 <- rtracklayer::import("/Users/catherinerohner/ETH/Bioinformatics/ENCFF008XKX.bed", format="narrowPeak")
H3K4me3 <- rtracklayer::import("/Users/catherinerohner/ETH/Bioinformatics/ENCFF247GVM.bed", format="narrowPeak")

H3K27me3_myocytes <- rtracklayer::import("/Users/catherinerohner/ETH/Bioinformatics/ENCFF561RIZmyocytes.bed", format="narrowPeak")
H3K4me3_myocytes <- rtracklayer::import("/Users/catherinerohner/ETH/Bioinformatics/ENCFF614PQBmyocytes.bed", format="narrowPeak")
```

```{r}
# Find overlaps between H3K27me3 and H3K4me3 peaks in mESC
overlaps_mESC <- findOverlaps(H3K27me3, H3K4me3)
# Extract the overlapping regions in mESC
b_domains_mESC <- reduce(c(H3K27me3[queryHits(overlaps_mESC)], H3K4me3[subjectHits(overlaps_mESC)]))
b_domains_mESC
```

```{r}
# Find overlaps between H3K27me3 and H3K4me3 peaks in myocytes
overlaps_myocytes <- findOverlaps(H3K27me3_myocytes, H3K4me3_myocytes)
# Extract the overlapping regions in myocytes
b_domains_myocytes <- reduce(c(H3K27me3_myocytes[queryHits(overlaps_myocytes)], H3K4me3_myocytes[subjectHits(overlaps_myocytes)]))
```

```{r}
# Overlap bivalent domains from mESC with H3K27me3 and H3K4me3 marks in myocytes
overlap_H3K27me3_myocytes <- countOverlaps(b_domains_mESC, H3K27me3_myocytes)
overlap_H3K4me3_myocytes <- countOverlaps(b_domains_mESC, H3K4me3_myocytes)
# Calculate overlaps with either mark or both in myocytes
overlap_all <- overlap_H3K27me3_myocytes + overlap_H3K4me3_myocytes
overlap_all

# Since we're adding the overlaps, some regions might be counted twice if they overlap with both marks.
# To find unique regions overlapping with either or both marks, we'll consider any overlap count > 0 as a unique overlap.
unique_overlaps_myocytes <- length(which(overlap_all > 0))
unique_overlaps_myocytes
```

Total overlap bewtween bivalent domains in mESC and histone marks in myocytes is 2,177 unique regions, that either overlap with H3K27me3 or H3K4me3 or both. Areas with high counts (up to7) as seen here might be an indicator of an area of intense regulatory activity. 
